### ISSUE TITLE
Vaccine Efficacy

### ISSUE THREAD

**Issue by nicofranzp** [phurichai/covid19macro#1]
Hi @phurichai,  

@fcordov and I were trying to compare the changes in mobility when using vaccines with different efficacies and noticed that the algorithm in [`seir_simple.py`](codes/seir_simple.py) does not update the efficacy in the projection --- i.e. only corrects the amount of people vaccinated in the data. Am I missing something?

Cheers!

**Comment by phurichai** [comment]
Hi @nicofranzp and @fcordov,

The efficacy assumptions are indeed fixed for the entire class `solveCovid`. If you wish to change these to other fixed constants, eg because you have better information about the vaccines used in your countries of interest, you can simply change lines 60-61 in `seir_simply.py`. If you want the efficacy to vary over time, you'd need to amend the dynamic function `step_seir` (see the modelling of reinfection rates there as an example). Or if you wish to have different efficacy rates across countries, then you'd need to have conditional statements within the class, something like
```
if self.iso2 == 'CH':
     self.vaccine = 'moderna'
```

If you want the efficacy of vaccine to decline because of virus mutations, then that is taken care of as a reinfection instance, which moves immune people into susceptible group again. The assumption here is that new vaccines will be tweaked quickly to be just as effective against new strains. But those vaccinated already could lose immunity as the old batch becomes obsolete.

**Comment by nicofranzp** [comment]
Hi @phurichai, 
Thanks for your reply!... I was thinking in the following: assume a country that has not started vaccinations yet (`vac_base_start_B` set to some date in the future). If you change the variable `self.effi_one` and `self.effi_two` to a ridiculous number, 1% and 2%, for example,  you will get the same projection than if you use 50% and 95%.  The easy way to solve this is to adjust the number of contracted dosages to an "effective" figure.

**Comment by phurichai** [comment]
Hi @nicofranzp 
Yes, vaccines that will arrive only in the future would not influence current mobility. This applies equally to the quantity of doses as well as efficacy rates. As shown in the paper, the social welfare function assumed implies an optimal mobility that only depends on the current sizes of S&I population and current infection/death rates. It's arguably a good proxy, as hardly any countries have re-opened in anticipation of vaccine arrival, but generally relax measures only once vaccination is sufficiently widespread (S is low). 

By the way, the assumption of vaccination paths (quantity of doses) has been updated some months ago and no longer depends on contracted dosages. Instead, countries are assigned to groups that differ in terms of projected vaccination speed. This projection grouping is periodically reviewed and updated to check that it is consistent with ongoing vaccine rollout. See lines 134-148 in ``seir_simple.py".

**Comment by nicofranzp** [comment]
Thanks! We´ll keep in touch
