### ISSUE TITLE
สอบถามเรื่องการกำหนดค่าตัวแปรครับ

### ISSUE THREAD

**Issue by sittiphansarapakdi** [phurichai/covid19macro#2]
ในไฟล์ param_simple.py ทำไมต้องเท่าเก่า -0.8 ครับ เลขนี้คือเลขอะไรหรอครับ แล้วท่าเป็นประเทศไทยตอนนี้ควรใช้เลขเท่าไหร่ครับเพราะอะไรหรอครับ

max_lockdown = -0.8  # Maximum lockdown

ในไฟล์ seir_simple.py
ค่า vac_scale คือะไรหรอครับ แล้วท่าเป็นประเทศไทยตอนนี้ควรใช้เลขเท่าไหร่ครับเพราะอะไรหรอครับ

        if self.iso2 in ['GB', 'US']:
            vac_scale = 1
        elif self.iso2 in ['BE', 'FR', 'DE', 'IT', 'NL', 'PL', 'SG', 'ES', 'CH', 'RO', 'CL', 'CA']:
            vac_scale = 0.8
        elif self.iso2 in ['AU', 'SA', 'SE', 'TR']:
            vac_scale = 0.65
        elif self.iso2 in ['AR', 'BR', 'MX', 'RU']:
            vac_scale = 0.50
        elif self.iso2 in ['ID', 'IN', 'JP', 'KR', 'MY']:
            vac_scale = 0.25
        elif self.iso2 in ['ZA']:
            vac_scale = 0.10

**Comment by phurichai** [comment]
_max_lockdown_ is the lower bound for mobility. It is set above -1 because a complete shutdown of all activity seems highly unlikely. In Thailand the lowest mobility index even got to was above -0.5 (early 2020). This constraint is for projection only and is in most cases not binding. It only kicks in when a country has an extremely rapid rise in cases.

_vac_scale_ is the proportion of population to be fully vaccinated by the end of 2021 (see line 152 in `seir_simple`).` Countries are assigned to different _vac_scale_ groups, depending on their actual progress to date. Thailand has been assigned to _vac_scale_=0.25 group. Please download the code again as 'TH' should be on the list.
